#define NUMBER_OF_ROWS 3
#define NUMBER_OF_COLS 3

#define EMPTY 0
#define OBSTACLE 1

const int map[NUMBER_OF_ROWS][NUMBER_OF_COLS] = {
  {OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE},
  {OBSTACLE, EMPTY, EMPTY, OBSTACLE},
  {OBSTACLE, OBSTACLE, OBSTACLE, OBSTACLE}
}
